export const majors = [
    "American Studies - General Option",
    "American Studies - Thematic Option",
    "Applied Biomedical Sciences - Clinical Science Option",
    "Applied Biomedical Sciences - Medical Laboratory Science Option",
    "Art - Animation & Interactive Media Concentration",
    "Art - Graphic Design Concentration",
    "Art - Studio Art Concentration ",
    "Biology - Bioinformatics Option",
    "Biology - Biotechnology Option",
    "Biology - Ecology Option",
    "Biology - Ecology, Evolution And Organismal Biology Option ",
    "Biology - General Option",
    "Biomedical Engineering ",
    "Business Administration - Accounting Concentration",
    "Business Administration - Entrepreneurship Concentration",
    "Business Administration - International Business Concentration",
    "Business Administration - Management Concentration",
    "Business Administration - Management Information Systems Concentration",
    "Business Administration - Marketing Concentration",
    "Business Administration - Supply Chain & Operations Management Concentration",
    "Business Administration, Analytics & Operations Management Concentration",
    "Business Administration, Finance Concentration",
    "Chemical Engineering - Bioengineering Option",
    "Chemical Engineering - Biological Engineering Option",
    "Chemical Engineering - General Option",
    "Chemical Engineering - Nanomaterials Engineering Option",
    "Chemical Engineering - Nuclear Engineering Option",
    "Chemistry - Biochemistry Option",
    "Chemistry - Forensic Science Option",
    "Chemistry - General Option",
    "Civil Engineering ",
    "Clinical Laboratory Sciences - Clinical Science Option",
    "Clinical Laboratory Sciences - Medical Laboratory Science Option",
    "Composition For New Media",
    "Computer Engineering ",
    "Computer Science - Bio-Cheminformatics Option",
    "Computer Science - Cybersecurity Option",
    "Computer Science - Data Science Option",
    "Computer Science - General Option",
    "Criminal Justice - Corrections Option",
    "Criminal Justice - Crime And Mental Health Option",
    "Criminal Justice - General Option ",
    "Criminal Justice - Homeland Security Option ",
    "Criminal Justice - Police Option",
    "Criminal Justice - Violence Option",
    "Digital Media",
    "Economics",
    "Education - Disability Studies For Educational And Community Organizations Option",
    "Education - Elementary And Moderate Disabilities Option",
    "Electrical Engineering ",
    "Electrical Engineering With Additional Major In Computer Science ",
    "Electrical Engineering With Additional Major In Physics",
    "Engineering Physics - Electrical & Computer Engineering Option",
    "Engineering Physics - Mechanical Engineering Option",
    "English - Creative Writing Concentration",
    "English - Journalism And Professional Writing Concentration",
    "English - Literature Concentration",
    "English - Theatre Arts Concentration",
    "Environmental Engineering ",
    "Environmental Science - Atmospheric Science Option",
    "Environmental Science - Environmental Geoscience Option",
    "Environmental Science - Environmental Science Option",
    "Environmental Science - Environmental Studies Option",
    "Environmental Science - Geoscience Option",
    "Environmental Science - Sustainability Option",
    "Environmental, Earth & Atmospheric Sciences",
    "Exercise Science - Clinical Option - 4 Year Degree",
    "Exercise Science - Exercise And Fitness Management Option",
    "Exercise Science, Clinical Option - 3-Year Degree",
    "Graphic Design",
    "History",
    "Industrial Engineering ",
    "Liberal Arts",
    "Mathematics ",
    "Mathematics - Applied Computational Mathematics Option",
    "Mathematics - Bioinformatics Option ",
    "Mathematics - Business Applications Option ",
    "Mathematics - Computer Science Option",
    "Mathematics - General Option",
    "Mathematics - Probability And Statistics Option",
    "Mathematics - Teaching Option",
    "Mechanical Engineering ",
    "Meteorology And Atmospheric Science",
    "Music Business",
    "Music Performance - Instrumental Option",
    "Music Performance - Voice Option",
    "Music Studies - General Option",
    "Music Studies - Instrumental Option",
    "Music Studies - Voice Option",
    "Nutritional Science - Dietetics Option",
    "Nutritional Science - General Option",
    "Nutritional Science - Nutrition And Wellness Option",
    "Peace And Conflict Studies",
    "Pharmaceutical Sciences - Pharmaceutical Marketing And Management Option",
    "Pharmaceutical Sciences, Pharmaceutical Marketing And Management Option - 3 Year Degree",
    "Philosophy - Communications & Critical Thinking Option",
    "Philosophy - General Option",
    "Philosophy - Philosophy & Religious Studies Option",
    "Physics - Astronomy And Astrophysics Option",
    "Physics - General Option",
    "Physics - Photonics Option",
    "Physics - Radiological Health Physics Option",
    "Plastics Engineering",
    "Political Science - American Politics Concentration",
    "Political Science - International Relations And Comparative Politics Concentration",
    "Political Science - Law & Politics Concentration",
    "Political Science - Sustainability And Environmental Politics Concentration",
    "Psychology - Behavior Analysis Concentration",
    "Psychology - Clinical Psychology Concentration ",
    "Psychology - Community Social Psychology Concentration",
    "Psychology - Developmental Disabilities Concentration",
    "Psychology - General Concentration",
    "Psychology - Health Psychology Concentration",
    "Public Health - Community Health/Health Promotion Concentration",
    "Public Health - Health Sciences Concentration",
    "Quantitative Economics",
    "Sociology - General Concentration",
    "Sociology - Policy & Social Problems Concentration",
    "Sociology - Racial Equity & Inclusion Concentration",
    "Sound Recording Technology ",
    "World Languages And Cultures - French Option",
    "World Languages And Cultures - French/Spanish Option",
    "World Languages And Cultures - Italian/Spanish Option",
    "World Languages And Cultures - Spanish Option",
];
