import Infocards from "@/components/Help/Card";
import Accordion from "@/components/Help/Accordion";
import Head from "next/head";
export default function App() {
    return (
        <>
            <Head>
                <title>HELP Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Infocards  />
                <br></br>
                <h1 className=" 
        hover:uppercase 
        w-1/2 
        m-auto
        flex
        justify-center
        ">
                    <b>Frequently Asks Questions</b>
                </h1>
                <Accordion/>
            </main>
        </>
      

    );
}
