import Head from "next/head";
import {useState, useEffect} from "react";


export default function Login() {
    const [didMount, setDidMount] = useState(false);
    useEffect(() => {
        setDidMount(true);
    }, []);

    if (!didMount) {
        return null;
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <script src="https://accounts.google.com/gsi/client" async defer></script>
            </Head>
            <main>
                <div className="mt-20 relative flex-col justify-center min-h-screen overflow-hidden">
                    <div className="w-full p-6 m-auto lg:max-w-xl">
                        <h1 className="text-3xl font-semibold text-left text-rowdy-blue">Login</h1>
                        <form className="mt-6">

                            <div className="mb-2">
                                <label htmlFor="email" className="block text-m font-semibold">Email or username</label>
                                <input type="email" className="block w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring focus:ring-opacity-40"/>
                            </div>

                            <div className="mb-2">
                                <label htmlFor="password" className="block text-m font-semibold">Password</label>
                                <input type="password" className="block w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring focus:ring-opacity-40"/>
                            </div>

                            <a href="#" className="text-m hover:underline">Forgot Password?</a>
                            
                            <div className="mt-6">
                                <button className="w-full px-4 py-2 tracking-wide text-white bg-rowdy-blue rounded-md transition-colors duration-200 transform focus:outline-none">
                                Login
                                </button>
                            </div>
                        </form>

                        <p className="mt-8 text-m font-light text-left">
                            Need an account?{" "}
                            <a href="sign-up" className="font-medium hover:underline">Sign up</a>
                        </p>

                        <p className="mt-4 text-m font-light text-left">or</p>

                        <p><br></br></p>

                        <div id="g_id_onload w-full"
                            data-client_id="793557852728-bjnm83d8lqunpbpbjl8kqvp976d3aptg.apps.googleusercontent.com"
                            data-login_uri="http://localhost:3000/login"
                            data-auto_prompt="false">
                        </div>
                        <div className="g_id_signin w-40"
                            data-type="standard"
                            data-size="large"
                            data-theme="outline"
                            data-text="sign_in_with"
                            data-shape="rectangular"
                            data-logo_alignment="left">
                        </div>

                    </div>
                </div>
            </main>
        </>
    );
}